# Database credentials
database:
  user: "debug"
  name: "beaconcha"
  host: "localhost"
  port: "5432"
  password: "debug"

# Chain network configuration (example will work for the prysm testnet)
chain:
  slotsPerEpoch: 32
  secondsPerSlot: 12
  genesisTimestamp: 1605693607
  minGenesisActiveValidatorCount: 16384

# Note: It is possible to run either the frontend or the indexer or both at the same time
# Frontend config
frontend:
  onlyAPI: false
  enabled: true # Enable or disable to web frontend
  imprint: "templates/imprint.example.html}**"  # Path to the imprint page content
  siteName: "Ethereum 2.0 Beacon Chain (Phase 0) Block Chain Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Showing the <a href='https://prylabs.net'>💎 Prysm Eth2 Testnet</a>" # Subtitle shown on the main page
  server:
    host: "0.0.0.0" # Address to listen on
    port: "3333" # Port to listen on
  database:
    user: "debug"
    name: "beaconcha"
    host: "localhost"
    port: "5432"
    password: "debug"
  sessionSecret: "<sessionSecret>"
  email:
    smtp:
      server: "<emailserver>"
      host: "<emailhost>"
      user: "<emailuser>"
      password: "<emailpassword>"
  flashSecret: "" # Encryption secret for flash cookies

# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  fullIndexOnStartup: false # Perform a one time full db index on startup
  indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  fetchBalances: false
  disableFullIndex: true
  oneTimeExport:
    enabled: true
    epochs: []
    startEpoch: 1
    endEpoch: 4
  node:
    host: "eth2-4000-prysm-v2.stage.bloxinfra.com" # Address of the backend node
    port: "80" # port of the backend node
    type: "prysm" # can be either prysm or lighthouse
    pageSize: 250 # the amount of entries to fetch per paged rpc call
  validatorCenter:
    network: "pyrmont"
    baseUrl: "http://vc.stage.bloxinfra.com/api"
    ssvAccounts: true
  eth1Endpoint: 'http://eth1.stage.bloxinfra.com:80'
  eth1DepositContractAddress: '0x8c5fecdc472e27bc447696f431e425d02dd46a8c'
  eth1DepositContractFirstBlock: 3743587
